apiVersion: apps/v1
kind: Deployment
metadata:
  name: security-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: security-service
  template:
    metadata:
      labels:
        app: security-service
    spec:
      containers:
      - name: security-service
        image: shreyaspatil67/security-service:v1
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: security-service
spec:
  selector:
    app: security-service
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP
